version: "3.7"
services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=microserviceDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
  microservice:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_DATABASE_NAME=microserviceDB
      - DB_DATABASE_DRIVER=postgres
